import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./state/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <div className="px-4 sm:px-8 min-h-[100vh] ">{children}</div>
        </ReduxProvider>
      </body>
    </html>
  );
}
